apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: p40wtfzwy-dotnet-basic
  janus-idp.io/tekton: p40wtfzwy-dotnet-basic
  backstage.io/kubernetes-id: p40wtfzwy-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: p40wtfzwy-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
